# Generated by Django 5.2.5 on 2026-07-28 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mekanik', '0002_workorder'),
        ('pembayaran', '0002_alter_jasaservis_id_alter_sparepart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailJasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.jasaservis')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_jasa', to='mekanik.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='DetailSparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.sparepart')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_sparepart', to='mekanik.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sparepart', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_jasa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_bayar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metode', models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('QRIS', 'QRIS')], max_length=20)),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Lunas', max_length=20)),
                ('workorder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='mekanik.workorder')),
            ],
        ),
    ]
