# Generated by Django 5.2.5 on 2026-07-28 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('service_advisor', 'Service Advisor'), ('mekanik', 'Mekanik'), ('kasir', 'Kasir'), ('pelanggan', 'Pelanggan')], default='pelanggan', max_length=50)),
                ('foto', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profile_pics/')),
                ('no_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
