# Generated by Django 6.0.6 on 2026-07-28 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mekanik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keahlian', models.CharField(max_length=100)),
                ('status_aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=50)),
                ('tipe', models.CharField(max_length=50)),
                ('plat_nomor', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_kendaraan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Proses', 'Proses'), ('Selesai', 'Selesai')], default='Menunggu', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_booking', to=settings.AUTH_USER_MODEL)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_booking_kendaraan', to='dashboard.kendaraan')),
                ('mekanik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_booking_mekanik', to='dashboard.mekanik')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(default='Tunai', max_length=50)),
                ('total_biaya', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas')], default='Belum Lunas', max_length=20)),
                ('tanggal_bayar', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_pembayaran_booking', to='dashboard.bookingservis')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosa', models.TextField(blank=True, null=True)),
                ('tindakan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Antrean', 'Antrean'), ('Dikerjakan', 'Dikerjakan'), ('Selesai', 'Selesai')], default='Antrean', max_length=20)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_wo_booking', to='dashboard.bookingservis')),
                ('mekanik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_wo_mekanik', to='dashboard.mekanik')),
            ],
        ),
    ]
