# Generated by Django 5.2.5 on 2026-07-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('service_advisor', 'Service Advisor'), ('pelanggan', 'Pelanggan'), ('mekanik', 'Mekanik'), ('kasir', 'Kasir')], default='pelanggan', max_length=20),
        ),
    ]
