# Generated by Django 5.2.5 on 2026-07-26 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('Motor', 'Motor'), ('Mobil', 'Mobil')], max_length=20)),
                ('merk', models.CharField(max_length=100)),
                ('tipe', models.CharField(max_length=100)),
                ('tahun', models.PositiveIntegerField()),
                ('nomor_polisi', models.CharField(max_length=20, unique=True)),
                ('warna', models.CharField(max_length=50)),
                ('nomor_rangka', models.CharField(blank=True, max_length=100, null=True)),
                ('nomor_mesin', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kendaraan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kendaraan',
                'verbose_name_plural': 'Data Kendaraan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingServis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_booking', models.DateField()),
                ('jam_booking', models.TimeField()),
                ('keluhan', models.TextField()),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diproses', 'Diproses'), ('dikerjakan', 'Dikerjakan'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='menunggu', max_length=20)),
                ('estimasi_selesai', models.DateField(blank=True, null=True)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kendaraan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.kendaraan')),
            ],
            options={
                'verbose_name': 'Booking Servis',
                'verbose_name_plural': 'Booking Servis',
                'ordering': ['-tanggal_booking', '-jam_booking'],
            },
        ),
    ]