# Generated by Django 6.0.6 on 2026-07-27 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('mekanik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosa', models.TextField()),
                ('tindakan', models.TextField()),
                ('status', models.CharField(choices=[('diproses', 'Diproses'), ('dikerjakan', 'Dikerjakan'), ('selesai', 'Selesai')], default='diproses', max_length=20)),
                ('tanggal_mulai', models.DateField(auto_now_add=True)),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workorder', to='booking.bookingservis')),
                ('mekanik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder', to='mekanik.mekanik')),
            ],
        ),
    ]
